/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.FoodDeliverySystem;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author akshatajadhav
 */
public class OrderHistoryJPanel extends javax.swing.JPanel {

    JLayeredPane customerTaskLayer;
    FoodDeliverySystem system;
    Customer customer;
    /**
     * Creates new form SysAdminManageCustomersJPanel
     */
    public OrderHistoryJPanel(JLayeredPane customerTaskLayer, FoodDeliverySystem system, Customer customer) {
        initComponents();
        this.customerTaskLayer=customerTaskLayer;
        this.system = system;
        this.customer = customer;
        tableRecordsStatus.setSize(tableRecordsStatus.getPreferredSize());
        orderHistoryTable.getColumn("Rating").setCellRenderer(new CellRenderer());
        populateTable();
    }

    public void displayCustomerTaskPanel(JPanel panel) {
        customerTaskLayer.removeAll();
        customerTaskLayer.add(panel);
        customerTaskLayer.repaint();
        customerTaskLayer.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableRecordsStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryTable = new javax.swing.JTable();

        tableRecordsStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableRecordsStatus.setText("No records available");

        setBackground(new java.awt.Color(255, 255, 255));

        orderHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Status", "Items", "Total ($)", "Feedback", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderHistoryTable);
        if (orderHistoryTable.getColumnModel().getColumnCount() > 0) {
            orderHistoryTable.getColumnModel().getColumn(0).setResizable(false);
            orderHistoryTable.getColumnModel().getColumn(0).setPreferredWidth(4);
            orderHistoryTable.getColumnModel().getColumn(1).setResizable(false);
            orderHistoryTable.getColumnModel().getColumn(1).setPreferredWidth(30);
            orderHistoryTable.getColumnModel().getColumn(2).setResizable(false);
            orderHistoryTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            orderHistoryTable.getColumnModel().getColumn(3).setResizable(false);
            orderHistoryTable.getColumnModel().getColumn(3).setPreferredWidth(15);
            orderHistoryTable.getColumnModel().getColumn(4).setResizable(false);
            orderHistoryTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    class CellRenderer implements TableCellRenderer{
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = orderHistoryTable.getColumn("Rating");
            orderHistoryTable.setRowHeight(20);
 
            return (Component) value;
        }
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderHistoryTable;
    private javax.swing.JLabel tableRecordsStatus;
    // End of variables declaration//GEN-END:variables
    private void populateTable() {
        JTable table = orderHistoryTable;
        int rowCount = table.getRowCount();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    
        for (Order o : system.getOrdersOfCustomer(customer)) {
            
            Object[] c = new Object[6];
            c[0] = o.getOrderId();
            c[1] = o.getOrderStatus();
            c[2] = o.getItemsAsString();
            c[3] = o.getTotal();
            c[4] = o.getFeedback();
            JLabel t = new JLabel();
            String stars = "/resources/sstar"+(o.getRating())+".png";
            t.setIcon(new ImageIcon(getClass().getResource(stars)));
            c[5] = t;
            model.addRow(c);
        }
        table.setModel(model);
        if (table.getRowCount() == 0) {
            table.add(tableRecordsStatus);
            table.setFillsViewportHeight(true);
        }
    }
}
