/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryPartnerRole;

import Business.DeliveryPartner.DeliveryPartner;
import Business.FoodDeliverySystem;
import Business.Menu.Menu;
import Business.Order.Order;
import userinterface.CustomerRole.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akshatajadhav
 */
public class ReadyToPickUpJPanel extends javax.swing.JPanel {

    FoodDeliverySystem system;
    DeliveryPartner deliveryPartner;
    JLayeredPane deliveryPartnerTaskLayer;
    List<Object> test = new ArrayList<>();

    /**
     * Creates new form SysAdminManageCustomersJPanel
     */
    public ReadyToPickUpJPanel(JLayeredPane deliveryPartnerTaskLayer, FoodDeliverySystem system, DeliveryPartner deliveryPartner) {
        initComponents();
        this.deliveryPartnerTaskLayer = deliveryPartnerTaskLayer;
        this.system = system;
        this.deliveryPartner = deliveryPartner;
        tableRecordsStatus.setSize(tableRecordsStatus.getPreferredSize());
        populateTable();
    }

    public void displayDeliveryPartnerTaskPanel(JPanel panel) {
        deliveryPartnerTaskLayer.removeAll();
        deliveryPartnerTaskLayer.add(panel);
        deliveryPartnerTaskLayer.repaint();
        deliveryPartnerTaskLayer.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableRecordsStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        readyToPickUpTable = new javax.swing.JTable();
        asssignMeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        tableRecordsStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableRecordsStatus.setText("No orders available to pick up!");

        setBackground(new java.awt.Color(255, 255, 255));

        readyToPickUpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order Id", "Customer", "Delivery Address ", "Resturant", "PickUp Address", "Items"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(readyToPickUpTable);
        if (readyToPickUpTable.getColumnModel().getColumnCount() > 0) {
            readyToPickUpTable.getColumnModel().getColumn(0).setResizable(false);
            readyToPickUpTable.getColumnModel().getColumn(1).setResizable(false);
            readyToPickUpTable.getColumnModel().getColumn(2).setResizable(false);
            readyToPickUpTable.getColumnModel().getColumn(3).setResizable(false);
            readyToPickUpTable.getColumnModel().getColumn(4).setResizable(false);
            readyToPickUpTable.getColumnModel().getColumn(5).setResizable(false);
        }

        asssignMeButton.setBackground(new java.awt.Color(92, 184, 92));
        asssignMeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        asssignMeButton.setForeground(new java.awt.Color(255, 255, 255));
        asssignMeButton.setText("PickUp!");
        asssignMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asssignMeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Select Orders!");

        cancelButton.setBackground(new java.awt.Color(92, 184, 92));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel!");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(asssignMeButton)
                        .addGap(116, 116, 116)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asssignMeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void asssignMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asssignMeButtonActionPerformed
        int row = readyToPickUpTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Select a order!", "Select", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String orderId = (String) readyToPickUpTable.getValueAt(row, 0);
        if(system.getOrderById(orderId).getOrderStatus().equalsIgnoreCase("Order picked up")){
            JOptionPane.showMessageDialog(this, "Order already ready for delivery!", "Order Status", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        system.getOrderById(orderId).setOrderStatus("Order picked up");
        system.getOrderById(orderId).setDeliveryPartner(deliveryPartner);
        populateTable();
    }//GEN-LAST:event_asssignMeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int row = readyToPickUpTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Select a order!", "Select", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String orderId = (String) readyToPickUpTable.getValueAt(row, 0);
        if(system.getOrderById(orderId).getOrderStatus().equalsIgnoreCase("Order picked up")){
            JOptionPane.showMessageDialog(this, "Once picked up you cannot cancel!", "Order Status", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        system.getOrderById(orderId).setOrderStatus("Declined by delivery partner! Restaurant will assign new partner");
        system.getOrderById(orderId).setDeliveryPartner(new DeliveryPartner());
        populateTable();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asssignMeButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable readyToPickUpTable;
    private javax.swing.JLabel tableRecordsStatus;
    // End of variables declaration//GEN-END:variables
    private void populateTable() {
        JTable table = readyToPickUpTable;
        int rowCount = table.getRowCount();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (Order o : system.getOrderByDeliveryPartner(deliveryPartner)) {
            if (o.getOrderStatus().equalsIgnoreCase("Order ready to pick up")) {
                Object[] c = new Object[6];
                c[0] = o.getOrderId();
                c[1] = o.getCustomer().getName();
                c[2] = o.getCustomer().getHomeAddress();
                c[3] = o.getRestaurant().getRestaurantName();
                c[4] = o.getRestaurant().getAddress();
                c[5] = o.getItemsAsString();
                model.addRow(c);
            }
        }
        table.getSelectedRow();
        table.setModel(model);
        if (table.getRowCount() == 0) {
            table.add(tableRecordsStatus);
            table.setFillsViewportHeight(true);
            asssignMeButton.setEnabled(false);
            cancelButton.setEnabled(false);
        } else {
            asssignMeButton.setEnabled(true);
            cancelButton.setEnabled(true);
        }
    }
}
