/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminRole;

import Business.Customer.Customer;
import Business.FoodDeliverySystem;
import Business.Restaurant.Restaurant;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author akshatajadhav
 */
public class AddRestaurantJPanel extends javax.swing.JPanel {

    FoodDeliverySystem system;
    JLayeredPane adminTaskLayer;
    /**
     * Creates new form SysAdminManageCustomersJPanel
     */
    public AddRestaurantJPanel(JLayeredPane adminTaskLayer, FoodDeliverySystem system) {
        initComponents();
        this.adminTaskLayer=adminTaskLayer;
        this.system = system;
    }

    public void displayAdminTaskPanel(JPanel panel) {
        adminTaskLayer.removeAll();
        adminTaskLayer.add(panel);
        adminTaskLayer.repaint();
        adminTaskLayer.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addressSignUpTextBox = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        passwordSignUpTextBox = new javax.swing.JPasswordField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        restaurantNameSignUpTextBox = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        managerNameSignUpTextBox = new javax.swing.JTextField();
        websiteSignUpTextBox = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        mobileNumberSignUpTextBox = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        usernameSignUpTextBox = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("ADD RESTAURANT");

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel25.setText("Website:");

        jLabel31.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel31.setText("Address:");

        addressSignUpTextBox.setText("Enter Address");
        addressSignUpTextBox.setBorder(null);
        addressSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressSignUpTextBoxMouseClicked(evt);
            }
        });

        passwordSignUpTextBox.setText("************");
        passwordSignUpTextBox.setBorder(null);
        passwordSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordSignUpTextBoxMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel29.setText("Restaurant Name:");

        restaurantNameSignUpTextBox.setText("Enter Name");
        restaurantNameSignUpTextBox.setBorder(null);
        restaurantNameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantNameSignUpTextBoxMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel30.setText("Manager Name:");

        managerNameSignUpTextBox.setText("Enter Name");
        managerNameSignUpTextBox.setBorder(null);
        managerNameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerNameSignUpTextBoxMouseClicked(evt);
            }
        });

        websiteSignUpTextBox.setText("Enter Web Address");
        websiteSignUpTextBox.setBorder(null);
        websiteSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                websiteSignUpTextBoxMouseClicked(evt);
            }
        });
        websiteSignUpTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteSignUpTextBoxActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel26.setText("Contact Number:");

        mobileNumberSignUpTextBox.setText("Enter Mobile Number");
        mobileNumberSignUpTextBox.setBorder(null);
        mobileNumberSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobileNumberSignUpTextBoxMouseClicked(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(92, 184, 92));
        submitButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("SUBMIT");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel24.setText("Username:");

        usernameSignUpTextBox.setText("Enter Username");
        usernameSignUpTextBox.setBorder(null);
        usernameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameSignUpTextBoxMouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel23.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(restaurantNameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobileNumberSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managerNameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(websiteSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(125, 125, 125)))
                    .addGap(104, 104, 104)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(usernameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(restaurantNameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(mobileNumberSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(passwordSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(managerNameSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(websiteSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(addressSignUpTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGap(0, 0, 0)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addressSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressSignUpTextBoxMouseClicked
        if(addressSignUpTextBox.getText().equals("Enter Address")){
            addressSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_addressSignUpTextBoxMouseClicked

    private void passwordSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordSignUpTextBoxMouseClicked
        if(passwordSignUpTextBox.getText().equals("************")){
            passwordSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_passwordSignUpTextBoxMouseClicked

    private void restaurantNameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantNameSignUpTextBoxMouseClicked
        if(restaurantNameSignUpTextBox.getText().equals("Enter Name")){
            restaurantNameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_restaurantNameSignUpTextBoxMouseClicked

    private void managerNameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerNameSignUpTextBoxMouseClicked
        if(managerNameSignUpTextBox.getText().equals("Enter Name")){
            managerNameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_managerNameSignUpTextBoxMouseClicked

    private void websiteSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_websiteSignUpTextBoxMouseClicked
        if(websiteSignUpTextBox.getText().equals("Enter Web Address")){
            websiteSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_websiteSignUpTextBoxMouseClicked

    private void websiteSignUpTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteSignUpTextBoxActionPerformed
        
    }//GEN-LAST:event_websiteSignUpTextBoxActionPerformed

    private void mobileNumberSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileNumberSignUpTextBoxMouseClicked
        if(mobileNumberSignUpTextBox.getText().equals("Enter Mobile Number")){
            mobileNumberSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_mobileNumberSignUpTextBoxMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String username = usernameSignUpTextBox.getText();
        String password = passwordSignUpTextBox.getText();
        String restaurantName = restaurantNameSignUpTextBox.getText();
        String managerName = managerNameSignUpTextBox.getText();
        String mobileNumber = mobileNumberSignUpTextBox.getText();
        String website = websiteSignUpTextBox.getText();
        String address = addressSignUpTextBox.getText();
        if(username.equals("Enter Username") || username.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please provide username", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!system.getUserAccountDirectory().isUsernameUnique(username)){
            JOptionPane.showMessageDialog(this, "Username already Exists", "Unique Username", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(password.equals("************") || password.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please provide password", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(restaurantName.equals("Enter Name") || restaurantName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide restaurant name", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;        
        }
        if(managerName.equals("Enter Name") || managerName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide manager name", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;        
        }
        if(mobileNumber.equals("Enter Mobile Number") || mobileNumber.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide mobile number", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(website.equals("Enter Web Address") || website.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide web address", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(address.equals("Enter Address") || address.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide address", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!mobileNumber.matches("^[0-9]{10}$")){
            JOptionPane.showMessageDialog(this, "Please provide correct mobile number", "Incorrect details", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!website.matches("^[a-zA-Z0-9]+.[a-zA-Z0-9]+.[a-zA-Z0-9]+$")){
            JOptionPane.showMessageDialog(this, "Please provide correct website", "Incorrect details", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long mobileNumberAsLong = Utils.phoneNoFromString(mobileNumber);
        
        Restaurant restaurant = new Restaurant(username, restaurantName, website, address, managerName, mobileNumberAsLong);
        
        UserAccount userAccount = new UserAccount();
        userAccount.setUsername(username);
        userAccount.setPassword(password);
        userAccount.setRole(new CustomerRole());
        
        system.newRestaurant(restaurant, userAccount);
        
        ManageRestaurantsJPanel mcjp = new ManageRestaurantsJPanel(adminTaskLayer, system);
        displayAdminTaskPanel(mcjp);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void usernameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameSignUpTextBoxMouseClicked
        if(usernameSignUpTextBox.getText().equals("Enter Username")){
            usernameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_usernameSignUpTextBoxMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressSignUpTextBox;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField managerNameSignUpTextBox;
    private javax.swing.JTextField mobileNumberSignUpTextBox;
    private javax.swing.JPasswordField passwordSignUpTextBox;
    private javax.swing.JTextField restaurantNameSignUpTextBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameSignUpTextBox;
    private javax.swing.JTextField websiteSignUpTextBox;
    // End of variables declaration//GEN-END:variables
}
