/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminRole;

import Business.Customer.Customer;
import Business.FoodDeliverySystem;
import Business.Restaurant.Restaurant;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.util.Date;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author akshatajadhav
 */
public class AddRestaurantJPanel extends javax.swing.JPanel {

    FoodDeliverySystem system;
    JLayeredPane adminTaskLayer;
    /**
     * Creates new form SysAdminManageCustomersJPanel
     */
    public AddRestaurantJPanel(JLayeredPane adminTaskLayer, FoodDeliverySystem system) {
        initComponents();
        this.adminTaskLayer=adminTaskLayer;
        this.system = system;
    }

    public void displayAdminTaskPanel(JPanel panel) {
        adminTaskLayer.removeAll();
        adminTaskLayer.add(panel);
        adminTaskLayer.repaint();
        adminTaskLayer.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addressSignUpTextBox = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        passwordSignUpTextBox = new javax.swing.JPasswordField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        restaurantNameSignUpTextBox = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        managerNameSignUpTextBox = new javax.swing.JTextField();
        websiteSignUpTextBox = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        mobileNumberSignUpTextBox = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        usernameSignUpTextBox = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cuisineSignUpTextBox = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Add Restaurant");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 0, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 10, 398, 12));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 9, 453, 13));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 368, 10));

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel25.setText("Website:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 92, 34));

        jLabel31.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel31.setText("Address:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 92, 34));

        addressSignUpTextBox.setText("Enter Address");
        addressSignUpTextBox.setBorder(null);
        addressSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressSignUpTextBoxMouseClicked(evt);
            }
        });
        add(addressSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 368, 30));
        add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 368, -1));

        passwordSignUpTextBox.setText("************");
        passwordSignUpTextBox.setBorder(null);
        passwordSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordSignUpTextBoxMouseClicked(evt);
            }
        });
        add(passwordSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 63, 368, 40));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 103, 368, 10));

        jLabel29.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel29.setText("Restaurant Name:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 155, 34));

        restaurantNameSignUpTextBox.setText("Enter Name");
        restaurantNameSignUpTextBox.setBorder(null);
        restaurantNameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantNameSignUpTextBoxMouseClicked(evt);
            }
        });
        add(restaurantNameSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 368, 40));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 368, 10));

        jLabel30.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel30.setText("Manager Name:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 139, 34));

        managerNameSignUpTextBox.setText("Enter Name");
        managerNameSignUpTextBox.setBorder(null);
        managerNameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerNameSignUpTextBoxMouseClicked(evt);
            }
        });
        add(managerNameSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 368, 40));

        websiteSignUpTextBox.setText("Enter Web Address");
        websiteSignUpTextBox.setBorder(null);
        websiteSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                websiteSignUpTextBoxMouseClicked(evt);
            }
        });
        websiteSignUpTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteSignUpTextBoxActionPerformed(evt);
            }
        });
        add(websiteSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 368, 40));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 368, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 368, 10));

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel26.setText("Contact Number:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 34));

        mobileNumberSignUpTextBox.setText("Enter Mobile Number");
        mobileNumberSignUpTextBox.setBorder(null);
        mobileNumberSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobileNumberSignUpTextBoxMouseClicked(evt);
            }
        });
        add(mobileNumberSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 368, 40));

        submitButton.setBackground(new java.awt.Color(92, 184, 92));
        submitButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("SUBMIT");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 117, 50));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel24.setText("Username:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 33, 92, 34));

        usernameSignUpTextBox.setText("Enter Username");
        usernameSignUpTextBox.setBorder(null);
        usernameSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameSignUpTextBoxMouseClicked(evt);
            }
        });
        add(usernameSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 63, 368, 40));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 103, 368, 10));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel23.setText("Password:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 33, 92, 34));

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        jLabel32.setText("Cuisine:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 92, 34));

        cuisineSignUpTextBox.setText("Enter Cuisine");
        cuisineSignUpTextBox.setBorder(null);
        cuisineSignUpTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuisineSignUpTextBoxMouseClicked(evt);
            }
        });
        cuisineSignUpTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineSignUpTextBoxActionPerformed(evt);
            }
        });
        add(cuisineSignUpTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 368, 40));
        add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 368, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void addressSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressSignUpTextBoxMouseClicked
        if(addressSignUpTextBox.getText().equals("Enter Address")){
            addressSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_addressSignUpTextBoxMouseClicked

    private void passwordSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordSignUpTextBoxMouseClicked
        if(passwordSignUpTextBox.getText().equals("************")){
            passwordSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_passwordSignUpTextBoxMouseClicked

    private void restaurantNameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantNameSignUpTextBoxMouseClicked
        if(restaurantNameSignUpTextBox.getText().equals("Enter Name")){
            restaurantNameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_restaurantNameSignUpTextBoxMouseClicked

    private void managerNameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerNameSignUpTextBoxMouseClicked
        if(managerNameSignUpTextBox.getText().equals("Enter Name")){
            managerNameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_managerNameSignUpTextBoxMouseClicked

    private void websiteSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_websiteSignUpTextBoxMouseClicked
        if(websiteSignUpTextBox.getText().equals("Enter Web Address")){
            websiteSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_websiteSignUpTextBoxMouseClicked

    private void websiteSignUpTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteSignUpTextBoxActionPerformed
        
    }//GEN-LAST:event_websiteSignUpTextBoxActionPerformed

    private void mobileNumberSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileNumberSignUpTextBoxMouseClicked
        if(mobileNumberSignUpTextBox.getText().equals("Enter Mobile Number")){
            mobileNumberSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_mobileNumberSignUpTextBoxMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String username = usernameSignUpTextBox.getText();
        String password = passwordSignUpTextBox.getText();
        String restaurantName = restaurantNameSignUpTextBox.getText();
        String managerName = managerNameSignUpTextBox.getText();
        String mobileNumber = mobileNumberSignUpTextBox.getText();
        String website = websiteSignUpTextBox.getText();
        String address = addressSignUpTextBox.getText();
        String cuisine = cuisineSignUpTextBox.getText();
        if(username.equals("Enter Username") || username.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please provide username", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!system.getUserAccountDirectory().isUsernameUnique(username)){
            JOptionPane.showMessageDialog(this, "Username already Exists", "Unique Username", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(password.equals("************") || password.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please provide password", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(restaurantName.equals("Enter Name") || restaurantName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide restaurant name", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;        
        }
        if(managerName.equals("Enter Name") || managerName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide manager name", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;        
        }
        if(mobileNumber.equals("Enter Mobile Number") || mobileNumber.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide mobile number", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(website.equals("Enter Web Address") || website.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide web address", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(address.equals("Enter Address") || address.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please provide address", "Empty Text Feilds", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!mobileNumber.matches("^[0-9]{10}$")){
            JOptionPane.showMessageDialog(this, "Please provide correct mobile number", "Incorrect details", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!website.matches("^[a-zA-Z0-9]+.[a-zA-Z0-9]+.[a-zA-Z0-9]+$")){
            JOptionPane.showMessageDialog(this, "Please provide correct website", "Incorrect details", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long mobileNumberAsLong = Utils.phoneNoFromString(mobileNumber);
        
        Restaurant restaurant = new Restaurant(username, restaurantName, address, cuisine, website, managerName, mobileNumberAsLong);
        
        UserAccount userAccount = new UserAccount();
        userAccount.setUsername(username);
        userAccount.setPassword(password);
        userAccount.setRole(new CustomerRole());
        
        system.newRestaurant(restaurant, userAccount);
        
        ManageRestaurantsJPanel mcjp = new ManageRestaurantsJPanel(adminTaskLayer, system);
        displayAdminTaskPanel(mcjp);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void usernameSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameSignUpTextBoxMouseClicked
        if(usernameSignUpTextBox.getText().equals("Enter Username")){
            usernameSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_usernameSignUpTextBoxMouseClicked

    private void cuisineSignUpTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuisineSignUpTextBoxMouseClicked
        if(cuisineSignUpTextBox.getText().equals("Enter Cuisine")){
            cuisineSignUpTextBox.setText("");
        }
    }//GEN-LAST:event_cuisineSignUpTextBoxMouseClicked

    private void cuisineSignUpTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineSignUpTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuisineSignUpTextBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressSignUpTextBox;
    private javax.swing.JTextField cuisineSignUpTextBox;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField managerNameSignUpTextBox;
    private javax.swing.JTextField mobileNumberSignUpTextBox;
    private javax.swing.JPasswordField passwordSignUpTextBox;
    private javax.swing.JTextField restaurantNameSignUpTextBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameSignUpTextBox;
    private javax.swing.JTextField websiteSignUpTextBox;
    // End of variables declaration//GEN-END:variables
}
